### ISSUE TITLE
about Align&Cropped Images

### ISSUE THREAD

**Issue by lzg188** [elvisyjlin/SpatialAttentionGAN#2]
hi，your work is great, but i want to know how to get the 128*128 Align&Cropped Images?

**Comment by lzg188** [comment]
my celea dadaset is 178*218

**Comment by lzg188** [comment]
i got it

**Comment by elvisyjlin** [comment]
Hi @lzg188,
The align&cropped images of CelebA is exactly 178x218. You can retrieve them from the official site provided in the readme.
