### ISSUE TITLE
why the result of color of glass is  light

### ISSUE THREAD

**Issue by lzg188** [elvisyjlin/SpatialAttentionGAN#3]
hi， i have other question, that is why the result of color of glass is  light

**Comment by elvisyjlin** [comment]
The generated images are restricted to the training dataset, which is the whole CelebA dataset in my example case. The network attempts to learn to draw faces with glasses similar to those in the dataset. The dataset might be dominated by light-colored glasses. It is a tricky problem with regard to data-driven learning. You can separate _sunglasses_ from the dataset If you'd like to generate faces with _sunglasses_ explicitly.

**Comment by lzg188** [comment]
yes, thank you for your reply
